import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { Config } from "../config.js";
import type { RecordStep } from "./record.js";
import { macroLocator } from "./refs.js";

const IRREVERSIBLE = /submit|send|buy|pay|delete|remove|publish|post|confirm/i;

export function isIrreversible(step: RecordStep): boolean {
  const hay = [step.op, step.target ?? "", step.value ?? ""].join(" ");
  return IRREVERSIBLE.test(hay);
}

function selectorFor(step: RecordStep): string {
  if (step.resolvedSelector) return step.resolvedSelector;
  if (step.target) return step.target;
  return "";
}

function sanitizeMacroName(s: string): string {
  return s.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 64) || "macro";
}

export async function compileMacro(
  config: Config,
  name: string,
  steps: RecordStep[],
): Promise<{ tsPath: string; mdPath: string; warnings: string[] }> {
  const safe = sanitizeMacroName(name);
  const dir = join(config.outputDir, "macros");
  await mkdir(dir, { recursive: true });

  const warnings: string[] = [];
  const irreversibleSteps = steps.filter(isIrreversible);
  if (irreversibleSteps.length > 0) {
    // Steps are human-facing here — 1-indexed, matching the .md step list
    warnings.push(
      `${irreversibleSteps.length} step(s) require approval: steps ${irreversibleSteps
        .map((s) => s.seq + 1)
        .join(", ")}`,
    );
  }

  // TS macro
  const tsLines: string[] = [
    `// macro: ${name} — generated by effing-use compile`,
    `// steps: ${steps.length}, requiresApproval: ${irreversibleSteps.length > 0}`,
    `import type { Page } from "playwright";`,
    ``,
    `export async function run(page: Page) {`,
  ];
  for (const s of steps) {
    const sel = selectorFor(s);
    const val = (s.value ?? "").slice(0, 500);
    const flag = isIrreversible(s) ? " // requiresApproval" : "";
    // Plan §6.2: macros must run standalone. An e-ref is session-scoped, so
    // it is never emitted as a live locator — an unresolved step becomes a
    // comment (and a warning) rather than a `page.locator("e2")` that throws.
    const unresolved = /^e\d+$/i.test(sel);
    if (unresolved) {
      warnings.push(
        `step ${s.seq + 1}: no stable selector for "${s.target ?? ""}" — emitted as a comment, add data-testid or a unique label and re-record`,
      );
    }
    const loc = macroLocator(sel);
    // An unresolved step must not break the file's syntax — emit a comment
    // line the user can act on, not `await /* ... */.click()`.
    if (unresolved) {
      tsLines.push(
        `  // SKIPPED step ${s.seq + 1}: ${s.op} "${s.target ?? ""}" has no stable selector (add a data-testid or a unique label, then re-record).`,
      );
      continue;
    }
    const staleNote =
      sel.startsWith("role=") || sel.startsWith("text=")
        ? " /* role+name selector: re-resolves at replay time */"
        : "";
    switch (s.op) {
      case "click":
        tsLines.push(`  await ${loc}.click();${flag}${staleNote}`);
        break;
      case "fill":
        tsLines.push(
          `  await ${loc}.fill(${JSON.stringify(val)});${flag}${staleNote}`,
        );
        break;
      case "press":
        tsLines.push(
          `  await page.keyboard.press(${JSON.stringify(val || s.target || "Enter")});${flag}`,
        );
        break;
      case "goto":
      case "open":
        tsLines.push(
          `  await page.goto(${JSON.stringify(val || sel)});${flag}`,
        );
        break;
      default:
        tsLines.push(
          `  // ${JSON.stringify(s.op)} ${JSON.stringify(sel)} ${JSON.stringify(val)}${flag}`,
        );
        break;
    }
  }
  tsLines.push(`}`);
  tsLines.push(``);

  const tsPath = join(dir, `${safe}.ts`);
  await writeFile(tsPath, tsLines.join("\n"), "utf-8");

  // SKILL.md
  const mdLines: string[] = [
    `# Skill: ${safe}`,
    ``,
    `When to use: replay this ${steps.length}-step flow via \`browser_act action=replay value=${safe}\`.`,
    ``,
    `## Steps`,
    ...steps.map((s) =>
      `${s.seq + 1}. ${s.op} ${s.target ?? ""} ${s.value ?? ""}${isIrreversible(s) ? " (requires approval)" : ""}`.trim(),
    ),
    ``,
    `## Verification`,
    irreversibleSteps.length > 0
      ? `This macro contains irreversible steps — replay will pause with E_APPROVAL_REQUIRED until approve:true.`
      : `No approval-gated steps.`,
    ``,
    `## Inputs`,
    `None in v1 — values are baked in. Parameterize in a future version if needed.`,
  ];
  const mdPath = join(dir, `${safe}.md`);
  await writeFile(mdPath, mdLines.join("\n"), "utf-8");

  return { tsPath, mdPath, warnings };
}
